"""Pairing codes (Track B — B2): the provisioning gate for enrollment.

Plan ("Pairing codes"):

- Generated by the **admin** only (``pairing.generate`` permission, checked
  at the API layer).
- Expiry: 1 day (default) / 1 week / 1 month — admin's choice.
- Single-use: admin-issued family/sub-admin codes are consumed on first
  successful pairing (the hub's own bootstrap admin code below is the exception).
- Role + room scope are baked into the code at generation time, so the
  enrolling phone never gets to pick its own privileges.
- Redemption is throttled per ``(source, purpose)`` (plan: "pairing-code
  entry" is a secret-guessing surface; 5 tries -> escalating wall keeps
  the 8-char code brute-force-proof). ``purpose`` is the request's
  network class (LAN vs remote — Phase 5 / D5), so remote redemption
  bursts can never exhaust the lockout counter the owner's on-LAN
  bootstrap claim answers to, even where a proxy / CIDR-widening change
  makes both arrive with the same source string.
- Every code carries a CLASS (Phase 1): ``bootstrap`` (the owner claim,
  LAN-only forever) vs ``member`` (admin-minted, remotely redeemable once
  the hub's ``remote_pairing_enabled`` flag is on — enforced in ``redeem``
  via ``remote_source``, gated at the API layer).

Bootstrap: the hub's *initial* pairing code (the printed sticker, plan
B3 / factory-reset flow) is an admin-role code generated by the hub
itself when no admin is enrolled. It never expires and is only redeemable
while the hub has no admin; its hash is persisted in hub_config and
re-installed on every boot, so the SAME printed sticker is dead weight
once an owner is paired and live again after a factory reset.

Codes are stored hashed (SHA-256). The 8-char alphanumeric space (~2^38)
plus the escalating throttle is brute-force-proof; hashing also keeps
plaintext secrets out of DB reads, backups, and log lines. The plaintext
is returned exactly once, at generation.

No HA imports — storage-table contract only, unit-testable on a temp
SQLite file. Storage-touching methods are synchronous: call via executor.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import secrets
import threading
import time
from typing import Any, Callable

try:
    from .auth_tokens import ROLE_ADMIN, ROLE_SUB_ADMIN, ROLE_USER
    from .throttle import FailureThrottle
except ImportError:  # top-level import in the test env (no HA package init)
    from auth_tokens import ROLE_ADMIN, ROLE_SUB_ADMIN, ROLE_USER  # type: ignore[no-redef]
    from throttle import FailureThrottle  # type: ignore[no-redef]

_LOGGER = logging.getLogger(__name__)

# Plan: admin chooses 1 day (default) / 1 week / 1 month.
EXPIRY_CHOICES: dict[str, float] = {
    "1d": 24 * 3600.0,
    "1w": 7 * 24 * 3600.0,
    "1m": 30 * 24 * 3600.0,
}
DEFAULT_EXPIRY = "1d"
# Roles an admin may hand out via pairing code. Admin codes exist only as
# the hub-generated bootstrap code (single-admin invariant stays with the
# auth engine either way — this is just the earlier, clearer refusal).
ISSUABLE_ROLES = (ROLE_SUB_ADMIN, ROLE_USER)
# 8 chars from an unambiguous alphabet (no 0/O, 1/I/L). The admin code is
# printed on the hub sticker and read by humans, so every character must be
# unmistakable. Mixed letters+digits, uppercase; redemption is normalized so it
# is case- and formatting-insensitive. ~2^38 space; the escalating per-IP
# throttle keeps it brute-force-proof despite the never-expiring bootstrap code.
CODE_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"
CODE_LEN = 8
# Storage key for the one bootstrap code (fixed id — there is only ever one).
BOOTSTRAP_CODE_ID = "bootstrap-admin"
# Code classes (pairing redesign Phase 1): redemption policy is decided per
# CLASS, not per network. The bootstrap owner claim stays LAN-only forever —
# first claim = physical possession, the documented TOFU anchor — while
# admin-minted member/share codes may be redeemed from any source once the
# hub's ``remote_pairing_enabled`` flag is on (checked at the API layer).
CODE_CLASS_BOOTSTRAP = "bootstrap"
CODE_CLASS_MEMBER = "member"
# Throttle purposes (Phase 5 / D5): the redeem throttle key is
# ``<purpose>:<source>``, one bucket per network class, so a remote
# lockout (e.g. every tunnel caller collapsing onto one loopback source,
# or a port proxy rewriting all sources to one IP) can never block the
# owner's LAN redemption from the same source string — and vice versa.
# ``FailureThrottle`` keys are caller-chosen strings by design; this
# composes the existing mechanism, it does not add a new one.
THROTTLE_PURPOSE_LAN = "lan"
THROTTLE_PURPOSE_REMOTE = "remote"


def _throttle_key(source_key: str, remote_source: bool) -> str:
    """The (source, purpose)-composed key for the redeem failure throttle."""
    purpose = THROTTLE_PURPOSE_REMOTE if remote_source else THROTTLE_PURPOSE_LAN
    return f"{purpose}:{source_key}"


class PairingError(Exception):
    """Pairing input rejected (bad role, bad expiry, bad rooms...)."""


class CodeInvalidError(PairingError):
    """Code unknown, expired, or already used — deliberately one bucket."""


class HubAlreadyClaimedError(PairingError):
    """The owner bootstrap code is correct but the hub already has an admin and
    the presenting device is NOT already enrolled — i.e. a DIFFERENT phone.
    Distinct from CodeInvalidError so enroll answers 'this hub is already paired'
    instead of the generic 'invalid code'. The SAME phone re-pairing never
    reaches here: enroll short-circuits it by public-key idempotency first."""


class LanOnlyCodeError(PairingError):
    """The code is VALID but its class may not be redeemed from a remote
    source — the bootstrap owner claim is LAN-only by design (physical
    possession). Same posture as HubAlreadyClaimedError: the secret was
    right, only the location wasn't, so the code is NOT consumed and no
    throttle slot is burned. Enroll answers with the same LAN-only 403 the
    network gate uses."""


def normalize_code(code: str) -> str:
    """Canonical form: uppercase, alphanumerics only (spaces/dashes dropped),
    so a code typed with stray spacing or lowercase still matches."""
    return "".join(ch for ch in code.upper() if ch.isalnum())


def hash_code(code: str) -> str:
    """SHA-256 of the NORMALIZED code — the single hashing path used by mint,
    redeem, and the stored permanent-code hash, so all three always agree."""
    return hashlib.sha256(normalize_code(code).encode("ascii")).hexdigest()


def _new_code() -> str:
    return "".join(secrets.choice(CODE_ALPHABET) for _ in range(CODE_LEN))


def _code_class(code_id: str, record: dict[str, Any]) -> str:
    """A stored code's class, fail-closed.

    Pre-Phase-1 records lack the ``code_class`` field, so classify by
    identity: the bootstrap code has the one fixed id, everything else was
    admin-minted (``generate_code`` only issues ISSUABLE_ROLES). Anything
    carrying the admin role is bootstrap-class regardless of stored metadata —
    an admin-granting code must never be remotely redeemable.
    """
    if (
        record.get("code_class") == CODE_CLASS_BOOTSTRAP
        or code_id == BOOTSTRAP_CODE_ID
        or record.get("role") == ROLE_ADMIN
    ):
        return CODE_CLASS_BOOTSTRAP
    return CODE_CLASS_MEMBER


class PairingManager:
    """Generate / list / revoke / redeem single-use pairing codes."""

    def __init__(
        self,
        codes_table: Any,
        admin_exists: Callable[[], bool],
        throttle: FailureThrottle | None = None,
    ) -> None:
        self._codes = codes_table
        self._admin_exists = admin_exists
        self.throttle = throttle or FailureThrottle("pairing")
        # Storage writes happen on executor threads; generation + redeem
        # both read-modify-write the table, so serialize them.
        self._lock = threading.Lock()

    # -- admin-facing ----------------------------------------------------------

    def generate_code(
        self,
        role: str,
        rooms: list[str] | None = None,
        expires_in: str = DEFAULT_EXPIRY,
        member_id: str | None = None,
    ) -> dict[str, Any]:
        """Mint a single-use code; the plaintext is returned ONLY here.

        ``member_id``, when given, is an EXISTING member's id — the device that
        redeems this code joins that person (shares their favorites/settings)
        instead of becoming a new one-device member. The caller passes the
        member's own role/rooms so the new device matches.
        """
        if member_id is not None and (
            not isinstance(member_id, str) or not member_id
        ):
            raise PairingError("member_id must be a non-empty string")
        if role not in ISSUABLE_ROLES:
            raise PairingError(
                f"Pairing role must be one of {', '.join(ISSUABLE_ROLES)}"
            )
        if rooms is not None and (
            not isinstance(rooms, list)
            or any(not isinstance(room, str) or not room for room in rooms)
        ):
            raise PairingError("rooms must be a list of area ids")
        # Plan: room-scoping is a per-USER toggle; sub-admins see all rooms.
        if rooms is not None and role != ROLE_USER:
            raise PairingError("Room scope only applies to the user role")
        ttl = EXPIRY_CHOICES.get(expires_in)
        if ttl is None:
            raise PairingError(
                f"expires_in must be one of {', '.join(EXPIRY_CHOICES)}"
            )

        with self._lock:
            self._purge_expired()
            code = _new_code()
            code_id = f"pair-{secrets.token_urlsafe(8)}"
            now = time.time()
            self._codes[code_id] = {
                "code_hash": hash_code(code),
                "role": role,
                "rooms": rooms,
                "member_id": member_id,
                "created_at": now,
                "expires_at": now + ttl,
                # Admin-minted = member class (ISSUABLE_ROLES only — the
                # bootstrap owner code is never minted here).
                "code_class": CODE_CLASS_MEMBER,
            }
        _LOGGER.info(
            "Pairing code %s generated (role=%s, expires_in=%s)",
            code_id,
            role,
            expires_in,
        )
        return {
            "code_id": code_id,
            "code": code,
            "role": role,
            "rooms": rooms,
            "member_id": member_id,
            "expires_at": int(now + ttl),
            "code_class": CODE_CLASS_MEMBER,
        }

    def list_codes(self) -> list[dict[str, Any]]:
        """Active codes — metadata only, never the code itself."""
        with self._lock:
            self._purge_expired()
            return [
                {
                    "code_id": code_id,
                    "role": record["role"],
                    "rooms": record.get("rooms"),
                    "created_at": int(record["created_at"]),
                    "expires_at": (
                        int(record["expires_at"]) if record["expires_at"] else None
                    ),
                    "bootstrap": code_id == BOOTSTRAP_CODE_ID,
                    "code_class": _code_class(code_id, record),
                }
                for code_id, record in self._codes.items()
            ]

    def revoke_code(self, code_id: str) -> bool:
        """Delete a code before it's used; True when it existed."""
        with self._lock:
            if code_id not in self._codes:
                return False
            del self._codes[code_id]
        _LOGGER.info("Pairing code %s revoked", code_id)
        return True

    def clear_all_codes(self) -> int:
        """Delete EVERY pairing code, the bootstrap admin code included; count.

        Wipes every code including the bootstrap admin code (afterwards none
        exists at all) — the factory-reset path. The "Regenerate pairing code"
        button calls this as part of a full pairing reset, then re-mints a
        fresh bootstrap admin code on the now-unclaimed hub via
        :meth:`ensure_bootstrap_code`.
        """
        with self._lock:
            count = len(self._codes)
            for code_id in list(self._codes):
                del self._codes[code_id]
        if count:
            _LOGGER.info(
                "Wiped all %d pairing code(s) — pairing factory reset", count
            )
        return count

    # -- enrollment gate ---------------------------------------------------------

    def authorize_known_device(
        self,
        code: str,
        source_key: str,
        remote_source: bool = False,
        *,
        allowed_hashes: tuple[str, ...] = (),
    ) -> None:
        """Gate the idempotent re-pair: the code must be one THIS hub owns.

        The enroll view short-circuits when it recognises a public key, so a
        phone re-running onboarding against its own claimed hub isn't bounced
        with "invalid code" (the bootstrap code is dead once an admin exists,
        so there is no code it *could* type). That leniency was too wide: it
        accepted ANY code, so a hub that merely REMEMBERS a phone would admit
        it on a code minted by a DIFFERENT hub. With two hubs on one LAN —
        an installer's bench hub and the client's real one, both holding the
        same phone key — the app's enroll chain takes the first hub that says
        yes, so typing the RIGHT hub's code could silently pair you to the
        WRONG hub, with every layer reporting success. That is exactly what
        happened on 2026-07-31.

        So: consume nothing, but require the code to be this hub's —

        * any code currently in the table (a member code we minted), or
        * one of ``allowed_hashes``: the persisted bootstrap/owner code (still
          this hub's own code although the live entry is dropped the moment an
          admin exists — that is what keeps the owner's re-onboarding working)
          and the hash of the code THIS device originally redeemed, so a
          double-submit or a retry after a mid-redeem timeout still passes
          even though that code was consumed on the first pass.

        Raises [CodeInvalidError] otherwise, throttled exactly like
        :meth:`redeem` so this path can't become a free code-guessing oracle.
        """
        throttle_key = _throttle_key(source_key, remote_source)
        self.throttle.check(throttle_key)
        if not isinstance(code, str) or not code.strip():
            self.throttle.record_failure(throttle_key)
            raise CodeInvalidError("Invalid pairing code")
        code_hash = hash_code(code)

        with self._lock:
            self._purge_expired()
            known = any(
                record["code_hash"] == code_hash
                for record in self._codes.values()
            )
        if not known:
            known = any(
                hmac.compare_digest(code_hash, allowed)
                for allowed in allowed_hashes
                if allowed
            )
        if not known:
            self.throttle.record_failure(throttle_key)
            raise CodeInvalidError("Invalid pairing code")
        self.throttle.clear(throttle_key)

    def redeem(
        self, code: str, source_key: str, remote_source: bool = False
    ) -> dict[str, Any]:
        """Consume a code; returns its role + room scope, or raises.

        ``source_key`` identifies the guesser (the request's remote IP) —
        every failure counts against it (ThrottledError once the wall is
        up). Failures are one generic bucket: unknown, expired, and
        already-used codes are indistinguishable to the caller.

        ``remote_source`` (Phase 1): True when the request did NOT come from
        the hub's own LAN (the API layer only lets such a request this far
        when ``remote_pairing_enabled`` is on). Member-class codes redeem
        normally; the bootstrap owner claim raises LanOnlyCodeError without
        consuming the code or burning a throttle slot.

        Throttling is per ``(source, purpose)`` (Phase 5 / D5): LAN and
        remote redemption count against SEPARATE buckets of the same
        escalating throttle, so a remote guessing burst locked out at the
        wall cannot block the owner's on-LAN claim from an identical
        source string — and a LAN lockout cannot block legitimate remote
        member redemption.
        """
        throttle_key = _throttle_key(source_key, remote_source)
        self.throttle.check(throttle_key)
        if not isinstance(code, str) or not code.strip():
            self.throttle.record_failure(throttle_key)
            raise CodeInvalidError("Invalid pairing code")
        code_hash = hash_code(code)

        with self._lock:
            self._purge_expired()
            match = next(
                (
                    (code_id, record)
                    for code_id, record in self._codes.items()
                    if record["code_hash"] == code_hash
                ),
                None,
            )
            if match is None:
                self.throttle.record_failure(throttle_key)
                raise CodeInvalidError("Invalid pairing code")
            code_id, record = match
            code_class = _code_class(code_id, record)
            # Class policy BEFORE any claim-state answer: a remote caller
            # never learns whether the hub is claimed. Bootstrap-class stays
            # LAN-only (physical possession); the code survives for the
            # legitimate on-LAN claim, and — like HubAlreadyClaimedError —
            # a code that was actually right burns no throttle slot.
            if remote_source and code_class != CODE_CLASS_MEMBER:
                raise LanOnlyCodeError(
                    "This pairing code can only be redeemed on the hub's own network"
                )
            # The bootstrap admin code dies the moment an admin exists —
            # a leaked install card is useless on a claimed hub.
            if code_id == BOOTSTRAP_CODE_ID and self._admin_exists():
                # Correct owner code on a claimed hub. The SAME phone is already
                # short-circuited (idempotent enroll) BEFORE redeem, so this is a
                # DIFFERENT phone — answer plainly, and don't burn a throttle slot
                # on a code that was actually right.
                raise HubAlreadyClaimedError("This hub is already paired")
            del self._codes[code_id]  # single-use, consumed even pre-enroll

        self.throttle.clear(throttle_key)
        _LOGGER.info(
            "Pairing code %s redeemed (role=%s, class=%s%s)",
            code_id,
            record["role"],
            code_class,
            ", remote" if remote_source else "",
        )
        # ``code_id`` lets the enroll path record which code a device used
        # (``enrolled_via``), retained for potential per-code revocation. The
        # bootstrap code is single-per-hub and never regenerated, so its id
        # flows through harmlessly.
        return {
            "role": record["role"],
            "rooms": record.get("rooms"),
            "code_id": code_id,
            "member_id": record.get("member_id"),
            "code_class": code_class,
        }

    # -- bootstrap ---------------------------------------------------------------

    def ensure_bootstrap_code(self) -> str | None:
        """Make sure an unclaimed hub has its initial admin pairing code.

        Returns the plaintext code when a NEW one was just minted (so setup
        can surface it to the installer), else None. No-op once an admin is
        enrolled or while a bootstrap code is already outstanding.
        """
        with self._lock:
            if self._admin_exists():
                # Claimed hub: an outstanding bootstrap code is dead weight.
                if BOOTSTRAP_CODE_ID in self._codes:
                    del self._codes[BOOTSTRAP_CODE_ID]
                return None
            if BOOTSTRAP_CODE_ID in self._codes:
                return None
            code = _new_code()
            self._codes[BOOTSTRAP_CODE_ID] = {
                "code_hash": hash_code(code),
                "role": ROLE_ADMIN,
                "rooms": None,
                "created_at": time.time(),
                "expires_at": None,  # redeemable until an admin exists
                "code_class": CODE_CLASS_BOOTSTRAP,
            }
        _LOGGER.info("Bootstrap admin pairing code generated")
        return code

    def install_bootstrap_hash(self, code_hash: str) -> None:
        """Install the hub's PERMANENT bootstrap admin code from a stored hash.

        The acquire code is printed on a sticker once and must survive factory
        reset, so its hash is persisted in hub_config and re-installed here on
        every boot (instead of minting a fresh random code each time). Idempotent;
        mirrors :meth:`ensure_bootstrap_code`'s claimed-state gate — drops the
        code once an admin is enrolled, (re)installs it while the hub is unclaimed.
        """
        with self._lock:
            if self._admin_exists():
                if BOOTSTRAP_CODE_ID in self._codes:
                    del self._codes[BOOTSTRAP_CODE_ID]
                return
            self._codes[BOOTSTRAP_CODE_ID] = {
                "code_hash": code_hash,
                "role": ROLE_ADMIN,
                "rooms": None,
                "created_at": time.time(),
                "expires_at": None,  # redeemable until an admin exists
                "code_class": CODE_CLASS_BOOTSTRAP,
            }

    # -- housekeeping --------------------------------------------------------------

    def _purge_expired(self) -> None:
        """Drop expired codes (caller holds the lock)."""
        now = time.time()
        for code_id in [
            cid
            for cid, record in self._codes.items()
            if record.get("expires_at") and record["expires_at"] <= now
        ]:
            del self._codes[code_id]
